language: "perl"
sudo: false
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.24-threads"
  - "5.24-shrplib"
  - "5.26"
  - "5.26-threads"
  - "5.26-shrplib"
  - "dev"
  - "blead"
install:
  - export AUTOMATED_TESTING=1 HARNESS_TIMER=1 AUTHOR_TESTING=0 RELEASE_TESTING=0
notifications:
  email:
    on_success: change
    on_failure: always
matrix:
  fast_finish: true
branches:
  except:
  - /^v?[0-9]+\.[0-9]+/
  - /^gitpan_version/
  - /^cpan_version/
  - /^cpan_path/
