language: "perl"
sudo: false
perl:
  - "5.6.2"
  - "5.8"               # normal preinstalled perl
  - "5.8.4"             # downloads a pre-built 5.8.4
  - "5.8.4-thr"         # pre-built 5.8.4 with threading
  - "5.8.8"             # downloads a pre-built 5.8.4
  - "5.8.8-thr"         # pre-built 5.8.4 with threading
  - "5.12.2"            # builds perl 5.12.2 from source (pre-built not available)
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.24-thr"
  - "5.26"
  - "5.26-thr"
  - "dev"
  - "dev-thr"
  - "blead"
  - "blead-thr"
install:
  - export AUTOMATED_TESTING=1 HARNESS_TIMER=1 AUTHOR_TESTING=0 RELEASE_TESTING=0
notifications:
  email:
    on_success: change
    on_failure: always
matrix:
  fast_finish: true
  include:
    - perl: 5.18
      env: COVERAGE=1   # enables coverage+coveralls reporting
  allow_failures:
    - perl: blead       # ignore failures for blead perl
branches:
  except:
  - /^v?[0-9]+\.[0-9]+/
  - /^gitpan_version/
  - /^cpan_version/
  - /^cpan_path/
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
